# Generated by Django 3.2.7 on 2021-09-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
